In [1]:
#!/usr/bin/env python

In [2]:
# -*- coding: utf-8 -*-

In [3]:
import numpy as np

In [4]:
import pandas as pd

In [5]:
import tqdm

In [6]:
import torch

In [7]:
import torch.nn.functional as F

In [8]:
from sklearn.linear_model import LinearRegression

In [9]:
from sklearn.model_selection import train_test_split

In [10]:
from sklearn.preprocessing import MinMaxScaler

In [11]:
from torch import nn

In [12]:
from torch import optim

In [13]:
# import python_libs

In [14]:
np.random.seed(42)

In [15]:
# parameters model

In [16]:
torch.manual_seed(42)

In [17]:
# parameters torch model

In [18]:
df = pd.read_csv('city.csv')

In [19]:
# download city.csv

In [20]:
df.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  lstat  medv  
0  396.90   4.98  24.0  
1  396.90   9.14  21.6  
2  392.83   4.03  34.7  
3  394.63   2.94  33.4  
4  396.90   5.33  36.2

In [21]:
# show head() city.csv

In [22]:
print(df.shape)

(506, 14)


In [23]:
# show shape() city.csv

In [24]:
Y = df['medv']

In [25]:
# show target(Y) city.csv

In [26]:
X = df.iloc[:, 0:12]
y = df.iloc[:, 12]

In [27]:
# show target(y) city.csv

In [28]:
X.head()

crim    zn  indus  chas    nox     rm   age     dis  rad  tax  ptratio  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296     15.3   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242     17.8   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242     17.8   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222     18.7   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222     18.7   

    black  
0  396.90  
1  396.90  
2  392.83  
3  394.63  
4  396.90

In [29]:
# show head() city.csv

In [30]:
print(y[:5])

0    4.98
1    9.14
2    4.03
3    2.94
4    5.33
Name: lstat, dtype: float64


In [31]:
# show target(y) city.csv

In [32]:
print(X.describe())

             crim          zn       indus        chas         nox          rm  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677083   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              age         dis         rad         tax     ptratio       black  
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000  
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032  
std     28.148861    2.105710 

In [33]:
# show describe() city.csv

In [34]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [35]:
# train = 0.8, test = 0.2

In [36]:
scaler = MinMaxScaler()

In [37]:
# SkLearn.MinMaxScaler()

In [38]:
X_train_scaled = scaler.fit_transform(X_train)

In [39]:
# transform X_train

In [40]:
X_test_scaled = scaler.transform(X_test)

In [41]:
# transform X_test

In [42]:
X_train_tensor = torch.Tensor(np.array(X_train_scaled))

In [43]:
# X_train transform tensor

In [44]:
X_test_tensor = torch.Tensor(np.array(X_test_scaled))

In [45]:
# X_test transform tensor

In [46]:
y_train_tensor = torch.Tensor(np.array(y_train))

In [47]:
# y_train transform tensor

In [48]:
y_test_tensor = torch.Tensor(np.array(y_test))

In [49]:
# y_test transform tensor

In [50]:
n_data, n_features = X_train_tensor.shape

In [51]:
# show shape() n_data, n_features

In [52]:
print(n_data)

404


In [53]:
# show shape() n_data

In [54]:
print(n_features)

12


In [55]:
# show shape() n_features

In [56]:
def loss(mean, target):
    """function loss"""
    return mean(F.l1_loss(input, target, reduction="none") / target) * 100

In [57]:
# function loss

In [58]:
loss_func = F.mse_loss

In [59]:
# loss_func

In [60]:
metrics_func_1 = [loss_func, loss]

In [61]:
# metrics_func_1

In [62]:
metrics_name = ["MSE", "LOSS"]

In [63]:
# metrics_name

In [64]:
def evaluate(model, metrics_func, x_1, y_1):
    """function evaluate"""
    metrics_value = []
    with torch.no_grad():
        for metric_func in metrics_func:
            metric_value = metric_func(torch.Tensor(X).flatten(), torch.Tensor(y).flatten())
            metrics_value.append(metric_value)
    return metrics_value

In [65]:
# function evaluate

In [66]:
def print_metrics(models, train_data, test_data, models_name):
    """function print_metrics"""
    results = np.ones(2 * len(models), len(metrics_func_1))
    models_name = []
    for model in models_name:
        models_name.extend([model + "Train", model + "Test"])
    for row, sample in enumerate([train_data, test_data]):
        results[row + sample * 2] = evaluate(models, metrics_func_1, sample[0], sample[1])
        results = pd.DataFrame(results, columns=metrics_name, index=models_name)
        return results

In [67]:
# function print_metrics

In [68]:
train_data_1 = (X_train_tensor, y_train_tensor)

In [69]:
# train_data_1

In [70]:
test_data_1 = (X_test_tensor, y_test_tensor)

In [71]:
# test_data_1

In [72]:
model_lr_sklearn = LinearRegression()

In [73]:
# SkLearn.LinearRegression()

In [74]:
model_lr_sklearn.fit(X_train_scaled, y_train)

LinearRegression()

In [75]:
# SkLearn.LinearRegression()

In [76]:
model_1 = [model_lr_sklearn.predict]

In [77]:
# model_lr_sklearn.predict

In [78]:
metrics_name = ["MSE", "LOSS"]

In [79]:
# metrics_name

In [80]:
models_name_1 = ["LOSS"]

In [81]:
# loss

In [82]:
model_lr = nn.Sequential(
    nn.Linear(in_features=n_features,
    out_features=1))

In [83]:
# torch model_lr

In [84]:
print(model_lr)

Sequential(
  (0): Linear(in_features=12, out_features=1, bias=True)
)


In [85]:
# torch model_lr

In [86]:
opt_lr = optim.SGD(params=model_lr.parameters(), lr=0.001)

In [87]:
# torch.optim model_lr

In [88]:
BATCH_SIZE_LR = 16

In [89]:
# torch batch

In [90]:
EPOCHS_LR = 1000

In [91]:
# torch epochs

In [92]:
for epoch in tqdm.trange(EPOCHS_LR):
    for i in range((n_data - 1) // BATCH_SIZE_LR + 1):
        start_i = i * BATCH_SIZE_LR
        end_i = start_i + BATCH_SIZE_LR
        Xb = X_train_tensor[start_i: end_i]
        yb = y_train_tensor[start_i: end_i]
        pred = yb
        loss_1 = loss_func(pred, yb + 1)

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 1998.59it/s]


In [93]:
# for epoch in tqdm.trange(EPOCHS_LR)

In [94]:
print(X_test)

         crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
173   0.09178   0.0   4.05     0  0.510  6.416   84.1  2.6463    5  296   
274   0.05644  40.0   6.41     1  0.447  6.758   32.9  4.0776    4  254   
491   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711   
72    0.09164   0.0  10.81     0  0.413  6.065    7.8  5.2873    4  305   
452   5.09017   0.0  18.10     0  0.713  6.297   91.8  2.3682   24  666   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
412  18.81100   0.0  18.10     0  0.597  4.628  100.0  1.5539   24  666   
436  14.42080   0.0  18.10     0  0.740  6.461   93.3  2.0026   24  666   
411  14.05070   0.0  18.10     0  0.597  6.657  100.0  1.5275   24  666   
86    0.05188   0.0   4.49     0  0.449  6.015   45.1  4.4272    3  247   
75    0.09512   0.0  12.83     0  0.437  6.286   45.0  4.5026    5  398   

     ptratio   black  
173     16.6  395.50  
274     17.6  396.90  
491     20.1  390.11  
72     

In [95]:
X_test

crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
173   0.09178   0.0   4.05     0  0.510  6.416   84.1  2.6463    5  296   
274   0.05644  40.0   6.41     1  0.447  6.758   32.9  4.0776    4  254   
491   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711   
72    0.09164   0.0  10.81     0  0.413  6.065    7.8  5.2873    4  305   
452   5.09017   0.0  18.10     0  0.713  6.297   91.8  2.3682   24  666   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
412  18.81100   0.0  18.10     0  0.597  4.628  100.0  1.5539   24  666   
436  14.42080   0.0  18.10     0  0.740  6.461   93.3  2.0026   24  666   
411  14.05070   0.0  18.10     0  0.597  6.657  100.0  1.5275   24  666   
86    0.05188   0.0   4.49     0  0.449  6.015   45.1  4.4272    3  247   
75    0.09512   0.0  12.83     0  0.437  6.286   45.0  4.5026    5  398   

     ptratio   black  
173     16.6  395.50  
274     17.6  396.90  
491     20.1  390.11  
72      19.2  390.91  
452     20.2  385.09  
..       ...     ...  
412     20.2   28.79  
436     20.2   27.49  
411     20.2   35.05  
86      18.5  395.99  
75      18.7  383.23  

[102 rows x 12 columns]

In [96]:
print(y_test)

173     9.04
274     3.53
491    18.07
72      5.52
452    17.27
       ...  
412    34.37
436    18.05
411    21.22
86     12.86
75      8.94
Name: lstat, Length: 102, dtype: float64


In [97]:
# y_test

In [98]:
def train(model_lr, loss_fn, optimizer):
    """function train"""
    size = len('city.csv')
    model_lr.train()
    for BATCH_SIZE_LR, (X, y) in tqdm.trange(EPOCHS_LR):
        X, y = X.to_device, y.to_device
        pred_1 = model_lr(X)
        loss = loss_fn(pred_1, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if BATCH_SIZE_LR % 16 == 0:
            loss_2 = loss.iten(), BATCH_SIZE_LR * len(X)
            print(f'loss: {loss_2}')

In [99]:
# function train

In [100]:
with torch.no_grad():
    print(model_lr(X_test_tensor[-1:]))

tensor([[0.3702]])


In [101]:
# X_test_tensor[-1:]

In [102]:
x_t = torch.Tensor([0.5141, 0.0000, 0.6430, 0.0000, 0.6337, 0.1334, 1.0000, 0.0481, 1.0000,
        0.9141, 0.8085, 0.2218])

In [103]:
# x_t

In [104]:
with torch.no_grad():
  print(model_lr(x_t))

tensor([0.3943])


In [105]:
# x_t

In [106]:
torch.save(model_lr, "lr.pth")

In [107]:
# torch.save(model_lr)

In [108]:
model_lr_1 = nn.Sequential(
    nn.Linear(in_features=n_features, out_features=16),
    nn.ReLU(),
    nn.Linear(in_features=16, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=32),
    nn.ReLU(),
    nn.Linear(in_features=32, out_features=1))

In [109]:
# torch model_lr_1

In [110]:
print(model_lr_1)

Sequential(
  (0): Linear(in_features=12, out_features=16, bias=True)
  (1): ReLU()
  (2): Linear(in_features=16, out_features=32, bias=True)
  (3): ReLU()
  (4): Linear(in_features=32, out_features=32, bias=True)
  (5): ReLU()
  (6): Linear(in_features=32, out_features=1, bias=True)
)


In [111]:
# torch model_lr_1

In [112]:
opt_lr_1 = optim.SGD(params=model_lr_1.parameters(), lr=0.0001)

In [113]:
# torch optim model_lr_1

In [114]:
BATCH_SIZE_LR_1 = 16

In [115]:
# torch batch

In [116]:
EPOCHS_LR_1 = 1000

In [117]:
# torch epochs

In [118]:
for epoch in tqdm.trange(EPOCHS_LR_1):
    for i in range((n_data - 1) // BATCH_SIZE_LR_1 + 1):
        start_i = i * BATCH_SIZE_LR_1
        end_i = start_i + BATCH_SIZE_LR_1
        Xb = X_train_tensor[start_i: end_i]
        yb = y_train_tensor[start_i: end_i]
        pred_2 = yb
        loss = loss_func(pred_2, yb + 1)

100%|█████████████████████████████████████| 1000/1000 [00:00<00:00, 2088.73it/s]


In [119]:
# for epoch in tqdm.trange(EPOCHS_LR_1)

In [120]:
print(X_test)

         crim    zn  indus  chas    nox     rm    age     dis  rad  tax  \
173   0.09178   0.0   4.05     0  0.510  6.416   84.1  2.6463    5  296   
274   0.05644  40.0   6.41     1  0.447  6.758   32.9  4.0776    4  254   
491   0.10574   0.0  27.74     0  0.609  5.983   98.8  1.8681    4  711   
72    0.09164   0.0  10.81     0  0.413  6.065    7.8  5.2873    4  305   
452   5.09017   0.0  18.10     0  0.713  6.297   91.8  2.3682   24  666   
..        ...   ...    ...   ...    ...    ...    ...     ...  ...  ...   
412  18.81100   0.0  18.10     0  0.597  4.628  100.0  1.5539   24  666   
436  14.42080   0.0  18.10     0  0.740  6.461   93.3  2.0026   24  666   
411  14.05070   0.0  18.10     0  0.597  6.657  100.0  1.5275   24  666   
86    0.05188   0.0   4.49     0  0.449  6.015   45.1  4.4272    3  247   
75    0.09512   0.0  12.83     0  0.437  6.286   45.0  4.5026    5  398   

     ptratio   black  
173     16.6  395.50  
274     17.6  396.90  
491     20.1  390.11  
72     

In [121]:
# X_test

In [122]:
print(y_test)

173     9.04
274     3.53
491    18.07
72      5.52
452    17.27
       ...  
412    34.37
436    18.05
411    21.22
86     12.86
75      8.94
Name: lstat, Length: 102, dtype: float64


In [123]:
# y_test

In [124]:
def train_1(model_lr_1, loss_fn, optimizer):
    """function_1 train_1"""
    size = len('city.csv')
    model_lr_1.train()
    for BATCH_SIZE_LR_1, (X, y) in tqdm.trange(EPOCHS_LR_1):
        X, y = X.to_device, y.to_device
        pred_3 = model_lr_1(X)
        loss = loss_fn(pred_3, y)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        if BATCH_SIZE_LR_1 % 16 == 0:
            loss_3 = loss.iten(), BATCH_SIZE_LR * len(X)
            print(f'loss: {loss_3}')

In [125]:
# function_1 train_1

In [126]:
with torch.no_grad():
    print(model_lr_1(X_test_tensor[-1:]))

tensor([[0.1262]])


In [127]:
# X_test_tensor[-1:]

In [128]:
torch.save(model_lr_1, "lr_1.pth")

In [129]:
# torch.save(model_lr_1)